# Generated by Django 6.0.8 on 2026-09-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoPurchaseFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copurchase_a', to='catalog.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copurchase_b', to='catalog.product')),
            ],
            options={
                'ordering': ['-count'],
                'unique_together': {('product_a', 'product_b')},
            },
        ),
    ]
